title : UBi
author: Team UB Mannheim

description: >-
  Agentic AI-Chatbot for UB Mannheim

execute:
  execute_notebooks: off
  
# Interact link settings
notebook_interface: "notebook"

# Launch button settings
repository:
  url: https://github.com/UB-Mannheim/UBi
  path_to_book: "docs"
  branch: main

html:
  home_page_in_navbar: false
  use_repository_button: true
